// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schedules.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSchedule = `-- name: CreateSchedule :execrows
INSERT INTO schedules (begin_datetime, end_datetime, course_id, facility_id, day)
VALUES ($1, $2, $3, $4, $5)
`

type CreateScheduleParams struct {
	BeginDatetime time.Time     `json:"begin_datetime"`
	EndDatetime   time.Time     `json:"end_datetime"`
	CourseID      uuid.NullUUID `json:"course_id"`
	FacilityID    uuid.UUID     `json:"facility_id"`
	Day           DayEnum       `json:"day"`
}

// Create a new schedule
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSchedule,
		arg.BeginDatetime,
		arg.EndDatetime,
		arg.CourseID,
		arg.FacilityID,
		arg.Day,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules WHERE course_id = $1
`

// Delete a schedule
func (q *Queries) DeleteSchedule(ctx context.Context, courseID uuid.NullUUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSchedule, courseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllSchedules = `-- name: GetAllSchedules :many
SELECT id, begin_datetime, end_datetime, course_id, facility_id, created_at, updated_at, day FROM schedules
`

// Get all schedules
func (q *Queries) GetAllSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, getAllSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.BeginDatetime,
			&i.EndDatetime,
			&i.CourseID,
			&i.FacilityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Day,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleByCourseID = `-- name: GetScheduleByCourseID :one
SELECT id, begin_datetime, end_datetime, course_id, facility_id, created_at, updated_at, day FROM schedules WHERE course_id = $1
`

// Get schedule by course_id
func (q *Queries) GetScheduleByCourseID(ctx context.Context, courseID uuid.NullUUID) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByCourseID, courseID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.BeginDatetime,
		&i.EndDatetime,
		&i.CourseID,
		&i.FacilityID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Day,
	)
	return i, err
}

const updateSchedule = `-- name: UpdateSchedule :execrows
UPDATE schedules
SET begin_datetime = $1, end_datetime = $2, course_id = $3, facility_id = $4, day = $5
WHERE course_id = $6
`

type UpdateScheduleParams struct {
	BeginDatetime time.Time     `json:"begin_datetime"`
	EndDatetime   time.Time     `json:"end_datetime"`
	CourseID      uuid.NullUUID `json:"course_id"`
	FacilityID    uuid.UUID     `json:"facility_id"`
	Day           DayEnum       `json:"day"`
	CourseID_2    uuid.NullUUID `json:"course_id_2"`
}

// Update a schedule
func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSchedule,
		arg.BeginDatetime,
		arg.EndDatetime,
		arg.CourseID,
		arg.FacilityID,
		arg.Day,
		arg.CourseID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
