services:
  db:
    image: 'postgres'
    container_name: '${COMPOSE_PROJECT_NAME}_db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'postgres'

  go-server:
    build:
      context: .
      dockerfile: dev.server.Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}_go_server'
    ports:
      - '80:80'
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./utils:/app/utils
      - ./docs:/app/docs
      - ./config:/app/config
    env_file:
      - ./config/.env
      - ./config/.env.local

  square-service:
    build:
      context: ./square_service
      dockerfile: Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}_square_service'
    ports:
      - '8000:8000'
    volumes:
      - ./square_service:/app
    env_file:
      - ./config/.env
      - ./config/.env.local