services:
  db:
   image: 'postgres'
   container_name: '${COMPOSE_PROJECT_NAME}_db'
   ports:
     - '5432:5432'
   environment:
     POSTGRES_USER: 'postgres'
     POSTGRES_PASSWORD: 'root'
     POSTGRES_DB: 'mydatabase'

  go-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}_go_server'
    ports:
      - '8080:8080'
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
    entrypoint: air
    env_file:
      - ./config/.env
      - ./config/.env.local