services:
  db:
    image: 'postgres'
    container_name: '${COMPOSE_PROJECT_NAME}_db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'mydatabase'

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'my_pgadmin'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}_go_server'
    ports:
      - '8080:8080'
    depends_on:
      - db