// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Model.AdvancedAthleteInfo", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerId");

                    b.ToTable("AdvancedAthleteInfo");
                });

            modelBuilder.Entity("Api.Model.BasicAthleteInfo", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<char?>("Gender")
                        .HasColumnType("character(1)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("CustomerId");

                    b.ToTable("BasicAthleteInfo");
                });

            modelBuilder.Entity("Api.Model.CourseSchedules.CourseSchedule", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("BeginTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("CourseId", "StartDate", "FacilityId", "BeginTime");

                    b.HasIndex("CoachId");

                    b.ToTable("CourseSchedules");
                });

            modelBuilder.Entity("Api.Model.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDateTime")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDateTime")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Api.Model.Facilities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacilityTypeId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Api.Model.Facilities.FacilityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FacilityTypes");
                });

            modelBuilder.Entity("Api.Model.Memberships.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDateTime")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDateTime")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Api.Model.People.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasConsentMarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasConsentMarketingSms")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<bool>("ShouldReceiveReceiptsForAllPayments")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Api.Model.People.Staff.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffTypeId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Api.Model.People.Staff.StaffType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StaffTypes");
                });

            modelBuilder.Entity("Api.Model.Permissions.StaffPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffTypeId");

                    b.ToTable("StaffPermissions");
                });

            modelBuilder.Entity("Api.Model.AdvancedAthleteInfo", b =>
                {
                    b.HasOne("Api.Model.People.Customers.Customer", "Customer")
                        .WithOne("AdvancedAthleteInfo")
                        .HasForeignKey("Api.Model.AdvancedAthleteInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Api.Model.BasicAthleteInfo", b =>
                {
                    b.HasOne("Api.Model.People.Customers.Customer", "Customer")
                        .WithOne("BasicAthleteInfo")
                        .HasForeignKey("Api.Model.BasicAthleteInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Api.Model.CourseSchedules.CourseSchedule", b =>
                {
                    b.HasOne("Api.Model.People.Staff.Staff", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Api.Model.Facilities.Facility", b =>
                {
                    b.HasOne("Api.Model.Facilities.FacilityType", "FacilityType")
                        .WithMany()
                        .HasForeignKey("FacilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("Api.Model.People.Customers.Customer", b =>
                {
                    b.HasOne("Api.Model.Courses.Course", null)
                        .WithMany("Customers")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("Api.Model.People.Staff.Staff", b =>
                {
                    b.HasOne("Api.Model.People.Staff.StaffType", "StaffType")
                        .WithMany("Staffs")
                        .HasForeignKey("StaffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffType");
                });

            modelBuilder.Entity("Api.Model.Permissions.StaffPermissions", b =>
                {
                    b.HasOne("Api.Model.People.Staff.StaffType", "StaffType")
                        .WithMany("Permissions")
                        .HasForeignKey("StaffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffType");
                });

            modelBuilder.Entity("Api.Model.Courses.Course", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Api.Model.People.Customers.Customer", b =>
                {
                    b.Navigation("AdvancedAthleteInfo");

                    b.Navigation("BasicAthleteInfo");
                });

            modelBuilder.Entity("Api.Model.People.Staff.StaffType", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
