// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Facility struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Location       string    `json:"location"`
	FacilityTypeID uuid.UUID `json:"facility_type_id"`
}

type FacilityType struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Schedule struct {
	ID            int32        `json:"id"`
	BeginDatetime time.Time    `json:"begin_datetime"`
	EndDatetime   time.Time    `json:"end_datetime"`
	CourseID      int32        `json:"course_id"`
	FacilityID    int32        `json:"facility_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	Day           int32        `json:"day"`
}
