// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: waivers.sql

package db

import (
	"context"
)

const createWaiverSignedStatus = `-- name: CreateWaiverSignedStatus :execrows
INSERT INTO waiver_signing (user_id, waiver_id, is_signed) VALUES ((SELECT id from users where email = $1), (SELECT id from waiver WHERE waiver_url = $2), $3)
`

type CreateWaiverSignedStatusParams struct {
	Email     string `json:"email"`
	WaiverUrl string `json:"waiver_url"`
	IsSigned  bool   `json:"is_signed"`
}

func (q *Queries) CreateWaiverSignedStatus(ctx context.Context, arg CreateWaiverSignedStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWaiverSignedStatus, arg.Email, arg.WaiverUrl, arg.IsSigned)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
