name: Run Tests

on:
  push:
    branches:
      - main  # Runs on every push to the main branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.23.4'  # Replace with the Go version you're using

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
            version: latest  # This sets up Docker Buildx, which works without systemd

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
            path: /tmp/.buildx-cache  # Path where Docker Buildx caches layers
            key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/go.mod', '**/go.sum') }}  # Cache key
            restore-keys: |
              ${{ runner.os }}-buildx-

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: |
          go test ./...
