name: Run Tests with Testcontainers

on:
  push:
    branches:
      - '**'           # Run on all branches
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install sqlc
        run: |
          # Download and install sqlc
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Set up Testcontainers environment
        run: echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV

      - name: Download Dependencies
        run: go mod tidy

      - name: Build Docker Image
        run: |
          docker build -t api-test:latest -f test.Dockerfile .  

      - name: Run Tests
        run: |
          docker run --rm -e STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}" api-test:latest
      
