name: Run Tests with Testcontainers

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Clean Go Modules Cache
        run: |
          go clean -cache
          go clean -modcache

      - name: Cache Go Modules
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Cache sqlc
        id: sqlc-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/sqlc
          key: sqlc-${{ runner.os }}-vlatest
          restore-keys: |
            sqlc-${{ runner.os }}-

      - name: Install sqlc
        if: steps.sqlc-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/sqlc
          GOBIN=~/.cache/sqlc go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Add sqlc to PATH
        run: echo "~/.cache/sqlc" >> $GITHUB_PATH

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Set up Testcontainers environment
        run: echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV

      - name: Download Dependencies
        run: go mod tidy

      - name: Run sqlc generate
        run: |
          cd internal/domains/event/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/game/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/haircut/event/persistence/sqlc && sqlc generate
          cd ../../../../../../
          cd internal/domains/haircut/haircut_service/persistence/sqlc && sqlc generate
          cd ../../../../../../
          cd internal/domains/identity/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/location/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/membership/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/program/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/payment/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/user/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd cmd/seed/sqlc && sqlc generate

      - name: Generate Swagger Documentation
        run: go run cmd/swag_init/swag-init.go

      - name: Run Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: true # Prevents cleanup failures in GitHub Actions
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: go test -v ./...