name: Run Tests with Testcontainers

on:
  push:
    branches:
      - '**'           # Run on all branches
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install sqlc
        run: |
          # Download and install sqlc
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Set up Testcontainers environment
        run: echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV

      - name: Download Dependencies
        run: go mod tidy

      - name: Run sqlc generate
        run: |
          cd internal/domains/course/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/enrollment/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/event/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/game/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/haircut/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/identity/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/location/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/membership/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/practice/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/purchase/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/team/persistence/sqlc && sqlc generate
          cd ../../../../../
          cd internal/domains/user/persistence/sqlc && sqlc generate

      - name: Run Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: true # Prevents cleanup failures in GitHub Actions
        run: go test -v ./...
