name: Run Tests with Testcontainers

on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Clean Go Modules Cache
        run: |
          go clean -cache
          go clean -modcache

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-
            go-mod-

      - name: Install sqlc
        uses: kjconroy/setup-sqlc@v1
        with:
          version: latest

      - name: Download Dependencies
        run: go mod tidy

      - name: Run sqlc generate
        run: |
          for dir in internal/domains/*/persistence/sqlc cmd/seed/sqlc; do
            (cd "$dir" && sqlc generate) || exit 1
          done

      - name: Run Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: go test -v -race ./...