name: Run Tests with Testcontainers

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Set up Testcontainers environment
        run: echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV

      - name: Download Dependencies
        run: go mod tidy

      - name: Run Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: true # Prevents cleanup failures in GitHub Actions
        run: go test -v ./...
