name: Update Swagger in Mobile

on:
  push:
    branches:
      - main  # Change this to match your API repo's default branch
    paths:
      - 'docs/**'
      - '.github/workflows/update-swagger.yml'

jobs:
  update-mobile-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API repository
        uses: actions/checkout@v4

      - name: Copy Swagger docs (excluding docs.go)
        run: |
          mkdir -p swagger-output  # Ensure the swagger-output directory exists
          
          # Check if swagger.json and swagger.yaml exist
          if [ ! -f docs/swagger.json ]; then
            echo "ERROR: swagger.json not found!" && exit 1
          fi
          if [ ! -f docs/swagger.yaml ]; then
            echo "ERROR: swagger.yaml not found!" && exit 1
          fi
          
          # Copy files to swagger-output
          cp docs/swagger.json swagger-output/
          cp docs/swagger.yaml swagger-output/

      - name: Upload Swagger docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: swagger-docs
          path: swagger-output/

      - name: Checkout Mobile Repository
        uses: actions/checkout@v4
        with:
          repository: Mostapha45/RiseMobile
          token: ${{ secrets.FRONTEND_REPO_PAT }}

      - name: Download Swagger docs artifact
        uses: actions/download-artifact@v4
        with:
          name: swagger-docs
          path: swagger-output


      - name: Copy new Swagger files to mobile
        run: |
          mkdir -p app/api/docs
          
          echo "Files in swagger-output before copying:"
          ls -l swagger-output

          # Directly copy files from swagger-output to frontend repo
          cp -rf swagger-output/* app/api/docs/
          
          git config --global user.email "klintlee1@gmail.com"
          git config --global user.name "KlintLee115"
          git add app/api/docs/
          git commit -m "Updated Swagger docs from API repo" || echo "No changes to commit"
          git push