steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sacred-armor-452904-c0/rise-square-service:$BUILD_ID', '-t', 'gcr.io/sacred-armor-452904-c0/rise-square-service:latest', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sacred-armor-452904-c0/rise-square-service:$BUILD_ID']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sacred-armor-452904-c0/rise-square-service:latest']

images:
- 'gcr.io/sacred-armor-452904-c0/rise-square-service:$BUILD_ID'
- 'gcr.io/sacred-armor-452904-c0/rise-square-service:latest'